services:
  dev:
    build:
      context: ..
      dockerfile: DockerFile

    command: sleep infinity
    volumes:
      - ../.:/workspace
    ports:
      - 8001:8000

    # Configure environment variables
    environment:
      XDEBUG_CONFIG: "client_host=127.0.0.1 client_port=9003"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
      MAILER_DSN: "smtp://maildev:1025"
      DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=11.2.4-MariaDB&charset=utf8mb4"
    networks:
      - tkc_demo

  # SGBD
  db_server:
    image: mariadb:11.2
    container_name: "${APP_NAME}-db"
    restart: always
    ports:
      - "33016:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - tkc_demo

  # GUI SGBD
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8101:80
    environment:
      PMA_HOST: db_server
    networks:
      - tkc_demo

  # Mailer
  maildev:
    image: maildev/maildev
    ports:
      - "1081:1080"
      - "1026:1025"
    networks:
      - tkc_demo

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
    networks:
      - tkc_demo

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - tkc_demo

networks:
  tkc_demo:

volumes:
  db_data:
  redis-insight:
