controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect_admin:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin'
